### Site metadata ###

title: Restaurant Recommender
description: "Restaurant Recommender"

github_username: stewseo

### Build settings ###

url: "https://stewseo.github.io/restaurant-recommendation-system"


# Build settings
remote_theme: abhinav/moonwalk

plugins:
  - jekyll-feed
  - jekyll-remote-theme
