### Site metadata ###

title: Restaurant Recommender
author: Stew Seo, Dannie Vo
description: > # this means to ignore newlines until "show_exerpts:"
  Restaurant Recommender

url: "https://stewseo.github.io/restaurant-recommendation-system"
baseurl:

github_username: stewseo

# Build settings
theme: just-the-docs

plugins:
  - jekyll-feed
  - jekyll-remote-theme
