
title: title
email: email@example.com
description: ...description...

url: "https://stewseo.github.io"
baseurl: "/restaurant-recommender"
github_username:  stewseo

remote_theme: just-the-docs/just-the-docs

color_scheme: "dark"

plugins:
  - github-pages
  - jekyll-remote-theme
  - jekyll-feed
