
title: Restaurant Recommender
email: Stewart.S.Seo@gmail.com
description: Restaurant Recommender

baseurl: "/restaurant-recommender"
url: "https://stewseo.github.io"

github_username:  stewseo, dvo0723

remote_theme: pmarsceill/just-the-docs

color_scheme: dark

plugins:
  - github-pages
  - jekyll-remote-theme
